# This is for docker desktop

# apiVersion: skaffold/v2alpha3
# kind: Config
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
# build:
#   local:
#     push: false
#   artifacts:
#     - image: ashwin2604/auth
#       context: auth
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: "src/**/*.ts"
#             dest: .

# This is for google cloud
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  googleCloudBuild:
    projectId: mern-microservices
  artifacts:
    - image: us.gcr.io/mern-microservices/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: us.gcr.io/mern-microservices/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .

    - image: us.gcr.io/mern-microservices/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .

    - image: us.gcr.io/mern-microservices/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .

    - image: us.gcr.io/mern-microservices/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: us.gcr.io/mern-microservices/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
